"""Initial Migration

Revision ID: 54af21e924cc
Revises: 
Create Date: 2022-05-15 16:21:57.599701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54af21e924cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_user_id_fkey', 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('blogs_user_id_fkey', 'blogs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
